config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cars#index"

  resources :cars

  resources :booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user

  acts_as_bookable  time_type: :range,
                    capacity_type: :none,
                    bookable_across_occurrences: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :cars

  acts_as_booker

  def check_author(item)  
    item.user_id == id
  end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class CarsController < ApplicationController

  before_action :load_booking, only: [:show, :edit, :update, :destroy]

  respond_to :html, :js, :json

  def index
    respond_with (@bookings = Car.all)
  end

  def show
    respond_with @car
  end

  def new
    respond_with (@car = current_user.cars.new)
  end

  def edit
  end

  def create
    # @car = current_user.cars.create(params[:car_params])
    # @saved = @car.save
    # respond_with @car, :location => @car if @saved
    @car = current_user.cars.create(car_params)
    if @car.save
      redirect_to @car, notice: 'Add car success'
    else
      render :new
    end
  end

  def update
    @car.update(car_params) if current_user.check_author(@car)
    respond_with @car
  end

  def destroy
    @car.destroy if current_user.check_author(@car)
    respond_with @car
  end

  private

  def load_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:id, :name, :body, :color, :fuel, :volume)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  before_action :load_car, only: [:show, :edit, :update, :destroy]

  respond_to :html, :js, :json

  def index
    respond_with (@cars = Car.all)
  end

  def show
    respond_with @car
  end

  def new
    respond_with (@car = current_user.cars.new)
  end

  def edit
  end

  def create
    # @car = current_user.cars.create(params[:car_params])
    # @saved = @car.save
    # respond_with @car, :location => @car if @saved
    @car = current_user.cars.create(car_params)
    if @car.save
      redirect_to @car, notice: 'Add car success'
    else
      render :new
    end
  end

  def update
    @car.update(car_params) if current_user.check_author(@car)
    respond_with @car
  end

  def destroy
    @car.destroy if current_user.check_author(@car)
    respond_with @car
  end

  private

  def load_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:id, :name, :body, :color, :fuel, :volume)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.slim
= render 'common/errors', resource: @car
.row
.col-lg-6.col-md-8.col-sm-12
  = form_for @car do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      p Type of body:
      = f.select(:body, options_for_select([['Sedan', 'Sedan'], ['Coupe', 'Coupe'],['Universal', 'Universal'], ['Hatchback', 'Hatchback']]))
    .form-group
      = f.label :color
      = f.text_field :color, class: 'form-control'
    .form-group
      p Fuel:
      = f.radio_button(:fuel, "true")
      = f.label(:fuel, "Petrol")
      = f.radio_button(:fuel, "false")
      = f.label(:fuel, "Disel")
    .form-group
      = f.label :volume
      = f.text_field :volume, class: 'form-control'
    div
      = f.submit 'Create', class: 'btn btn-primary'
                
  = link_to 'Back', cars_path, type: 'button', class: 'btn btn-default cancel'

app/views/cars/edit.html.slim
= render 'common/errors', resource: @car
.row
.col-lg-6.col-md-8.col-sm-12
  = form_for @car do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      p Type of body:
      = f.select(:body, options_for_select([['Sedan', 'Sedan'], ['Coupe', 'Coupe'],['Universal', 'Universal'], ['Hatchback', 'Hatchback']]))
    .form-group
      = f.label :color
      = f.text_field :color, class: 'form-control'
    .form-group
      p Fuel:
      = f.radio_button(:fuel, "true")
      = f.label(:fuel, "Petrol")
      = f.radio_button(:fuel, "false")
      = f.label(:fuel, "Disel")
    .form-group
      = f.label :volume
      = f.text_field :volume, class: 'form-control'
    div
      = f.submit 'Update', class: 'btn btn-primary'
      = button_tag 'Cancel', type: 'button', class: 'btn btn-default cancel'
                
  = link_to 'Back', cars_path, type: 'button', class: 'btn btn-default cancel'

app/views/cars/index.html.slim
p Cars:
ul#cars_list
  - if @cars.any?
    table class="table table-striped"
      thead
        tr
          th #
          th Name
          th Type of body
          th Color
          th Fuel
          th Volume
      - @cars.each do |car|
        tr
          td.name = car.id
          td.name = car.name
          td.body_type = car.body
          td.color = car.color
          -if car.fuel == true
            td.fuel Patrol
          -else
            td.fuel Disel
          td.volume = car.volume
          td.delete 
            = link_to 'Delete', [car], class: 'delete-car-link btn btn-default ', method: :delete, remote: true, data: {confirm: "Are you sure?"}
            = link_to 'Edit', edit_car_path(car), class: 'edit-car-link btn btn-default'

  - else
    p Cars not created
p = link_to 'Create car', new_car_path

app/views/cars/new.html.slim
h1 New Car
= render 'form'

app/views/cars/show.html.slim
p =@car.name
p =@car.body
p =@car.fuel

app/views/common/_errors.html.slim
- if resource.errors.any?
  .alert.alert-danger.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times;
    p Errors prohibited this record from being saved:
    ul
      - resource.errors.messages.each do |attribute, messages|
        - messages.each do |message|
          li= "#{attribute} #{message}"

app/views/common/_footer.html.slim
footer class="footer"
  .container
    p class="copyright"
      | &copy;&nbsp;2017 Artem Shevchenko. Rental Booking&nbsp;
      = link_to 'Github', 'https://github.com/Arshev/booking', target: '_blank'

app/views/common/_nav.html.slim
.navbar.navbar-default.navbar-static-top
  .container
    button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-responsive-collapse"
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand href="/" Rental Booking
    .navbar-collapse.collapse.navbar-responsive-collapse
      ul.nav.navbar-nav.navbar-right
        / li.search
        /   = render 'search/form'
        - if user_signed_in?
            li.navbar-text 
              = t('hello')  
              = current_user.email
            li = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-item nav-link'
        - else
            li = link_to 'Sign in', new_user_session_path, class: 'nav-item nav-link'

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="description" content=""
    meta name="author" content=""

    title Rental Booking
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    .wrapper
      = render 'common/nav'

      .container
        .main
        = bootstrap_flash
        = yield
      = render 'common/footer'

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.slim
p Hello World!